image: ubuntu:focal

stages:
  - Check
  - Test with Clang
  - Test with GCC
  - Build Documentation
  - Publish

.retry setting:
  retry:
    max: 2
    when: runner_system_failure

line count:
  extends: .retry setting
  stage: Check
  dependencies: []
  image: registry.gitlab.com/musicscience37_ci/cloc-docker:v1-1
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=extern,line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "3 mos"

static analysis:
  extends: .retry setting
  stage: Check
  dependencies: []
  image: musicscience37/clang-ci:clang10-v2.1
  before_script:
    - pip3 install junit2html
    - mkdir build_static_analysis
    - cd build_static_analysis
    - git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
    - cd ../
  script:
    - cmake -S ./ -B build_static_analysis
      -DMPRPC_ENABLE_CLANG_TIDY:BOOL=ON
      -DMPRPC_TESTING:BOOL=ON
      -DMPRPC_ENABLE_CPP_WARNINGS:BOOL=ON
    - cmake --build build_static_analysis
      --target mprpc_clang_tidy
    - scripts/check_clang_tidy.sh build_static_analysis/clang_tidy
  after_script:
    - cd build_static_analysis/clang_tidy
    - cat $(find $1 -name '*.txt') |
      python3 ../clang-tidy-to-junit/clang-tidy-to-junit.py $(dirname $(pwd)) > clang_tidy_junit.xml
    - python3 -m junit2htmlreport clang_tidy_junit.xml clang_tidy_junit.html
  artifacts:
    paths:
      - build_static_analysis
    reports:
      junit:
        - build_static_analysis/clang_tidy/clang_tidy_junit.xml
    when: always
    expire_in: "3 mos"

.release-test-base:
  extends: .retry setting
  needs: ["line count"]
  dependencies: []
  before_script:
    - pip3 install -r requirements.txt
    - pip3 install junitparser junit2html
    - chmod +xr /usr/local/bin/junitparser
    - apt update
    - apt install -y valgrind
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DMPRPC_TESTING:BOOL=ON
      -DMPRPC_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - ctest -M Experimental -T Configure -T Build -T Test -T MemCheck
    - ctest -M Experimental -T Submit
  after_script:
    - scripts/collect_test_results.sh $BUILD_DIR/junit
  artifacts:
    paths:
      - $BUILD_DIR
    reports:
      junit:
        - $BUILD_DIR/junit/mprpc_test_unified.xml
    when: always
    expire_in: "3 mos"

clang coverage:
  extends: .release-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang10-v2.1
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DMPRPC_TESTING:BOOL=ON
      -DMPRPC_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - ctest -M Experimental -T Build -T Test -T MemCheck -T Submit
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
  coverage: '/Line Coverage: \d+\.\d+/'

gcc coverage:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v2.1
  variables:
    BUILD_DIR: build_gcc_coverage
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DMPRPC_TESTING:BOOL=ON
      -DMPRPC_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=--coverage"
      "-DCMAKE_MODULE_LINKER_FLAGS=--coverage"
    - cd $BUILD_DIR
    - ctest -V -M Experimental -T Configure -T Build -T Test -T MemCheck
    - ctest -V -M Experimental -T Coverage || true
    - ctest -V -M Experimental -T Submit
    - cd ../
    - scripts/collect_gcc_coverage.sh build_gcc_coverage
  coverage: '/Total:\|\s*(\d+\.?\d+?)%/'

gcc-10:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v2.1
  variables:
    BUILD_DIR: build_gcc10

doc:
  extends: .retry setting
  stage: Build Documentation
  needs: ["line count"]
  dependencies: []
  image: musicscience37/sphinx-doxygen:v-2.1
  before_script:
    - pip3 install -r requirements.txt
  script:
    - mkdir build_doc
    - cmake -S ./ -B build_doc
      -DMPRPC_BUILD_DOC:BOOL=ON
      -DMPRPC_BUILD_LATEX_DOC:BOOL=ON
    - cmake --build build_doc --target mprpc_doc
  artifacts:
    paths:
      - build_doc
    when: always
    expire_in: "3 mos"

pages:
  extends: .retry setting
  stage: Publish
  only:
    - develop
  needs:
    - doc
    - gcc coverage
    - clang coverage
  dependencies:
    - doc
    - gcc coverage
    - clang coverage
  script:
    - mkdir public
    - mv build_doc/doc/sphinx/html public/sphinx
    - mv build_doc/doc/sphinx/latex/mprpc.pdf public/mprpc.pdf
    - mv build_doc/doc/doxygen/html public/doxygen
    - mv build_gcc_coverage/coverage/html public/gcc_coverage
    - mv build_clang_coverage/coverage/html public/clang_coverage
  artifacts:
    paths:
      - public
